### ISSUE TITLE
BUG: You made the styling too nice

### ISSUE THREAD

**Issue by MichaelArestad** [useIceberg/iceberg-editor#19]
### Describe the bug:
You made the styling and text choices too pleasant. Now I would like to see it as a front-end gberg theme. Just saying...

**Comment by phpbits** [comment]
haha! Thanks @MichaelArestad! We don't have plan for theme yet but this is not out of the possibilities. We'll keep you posted if ever we decided to do a front-end view with Iceberg styling on it. Thanks again!
