### ISSUE TITLE
Sometimes the cursor disappears

### ISSUE THREAD

**Issue by MichaelArestad** [useIceberg/iceberg-editor#21]
### Describe the bug
Sometimes the cursor disappears when working with paragraph text (and maybe more).

### To reproduce:
I'm not able to reliably reproduce. Will update if I figure it out. 

I'm on FF Mac Latest, Iceberg latest, Mustard Seed, Gberg plugin latest.

**Comment by phpbits** [comment]
@MichaelArestad Is this for the mouse cursor? Thanks!

**Comment by MichaelArestad** [comment]
I should have clarified. The blinking line that indicates where text will be added sometimes is missing.

**Comment by phpbits** [comment]
I see. It's how the core editor works, when you focus on other components, for example click on themer or more menu the focus(blinking line) will be gone. I hope this answers your questions, it works the same when you are on Gutenberg editor mode.

![Screen Capture on 2020-05-29 at 00-29-22](https://user-images.githubusercontent.com/3365507/83168062-86858700-a143-11ea-9bd2-ca6cfeb4452c.gif)

**Comment by MichaelArestad** [comment]
That makes sense. I figured it might be something like that.
