### ISSUE TITLE
Enable Iceberg for specific post types / disable for regular posts

### ISSUE THREAD

**Issue by binaryfire** [useIceberg/iceberg-editor#29]
Hi guys,

Would love to get an option to enable Iceberg for specific custom post types, as well as disable it for regular posts and pages. For example I want to use Iceberg on a "Notes" CPT and nowhere else. I'm sure there are plenty of other use cases too :)

**Comment by richtabor** [comment]
Interesting idea, are you envisioning a programmatic approach?

**Comment by binaryfire** [comment]
@richtabor Sorry about the late reply! A programmatic approach would be fine for me. Maybe some kind of filter? But a settings page with checkboxes to select post types may be easier for regular users.
