### ISSUE TITLE
ISBAT to use checkbox clearly

### ISSUE THREAD

**Issue by phpbits** [useIceberg/iceberg-editor#50]
@richtabor The custom checkbox visibility is not displaying correctly. Interaction with these checkboxes is working but UI isn't. Thanks!

<img width="666" alt="Screen Shot 2021-03-14 at 5 05 06 AM" src="https://user-images.githubusercontent.com/3365507/111044332-d939f080-8482-11eb-807d-d5a767c0ca39.png">

**Comment by richtabor** [comment]
It looks like this isn't working here? https://github.com/useIceberg/iceberg-editor/blob/master/src/components/options-modal/enable-panel.js#L18

**Comment by phpbits** [comment]
@richtabor I've created a PR for the fixes regarding this issue. Thanks!
https://github.com/useIceberg/iceberg-editor/pull/54
