### ISSUE TITLE
npm setup doesn't seem to be the right command. 

### ISSUE THREAD

**Issue by johnstonphilip** [useIceberg/iceberg-editor#6]
### Describe the bug:
The instructions say to run `npm setup` to install dependencies, but I think the command should be `npm run setup`. Running `npm run setup` works for me.

### To reproduce:
Attempt to run `npm setup` on the command line. Notice you get a response that gives npm instructions, instead of the command running. 

### Expected behavior:
The npm setup procedure exectues.

**Comment by phpbits** [comment]
@johnstonphilip You can use `npm install` to install dependencies. Thanks!

**Comment by johnstonphilip** [comment]
https://github.com/useIceberg/iceberg-editor/pull/8

**Comment by janboddez** [comment]
`npm run setup` does more than just `npm install`, though. According to `package.json`, it's equal to `composer install && npm install && NODE_ENV=development wp-scripts start` ...

**Comment by richtabor** [comment]
Closed by #8.
