### ISSUE TITLE
Iceberg is used no matter what

### ISSUE THREAD

**Issue by johnstonphilip** [useIceberg/iceberg-editor#7]
### Describe the bug:
When I click on "Edit" I expect Gutenberg to be used. I expect Iceberg to only be used when I click on "Edit (Iceberg)".

<img width="351" alt="Screen Shot 2020-05-20 at 11 05 09 AM" src="https://user-images.githubusercontent.com/7538525/82462847-182d2e80-9a8a-11ea-96a7-ac52b6c76f1e.png">

### To reproduce:
1. Create a new post using Iceberg.
2. Click "Edit", and notice it does not open with Gutenberg, but with Iceberg.

### Expected behavior:
I expect Iceberg to only be used when I click on "Edit (Iceberg)".

### Side thought:
This whole problem makes me think that core needs a proper "editor selector" solution, allowing you to pick your editor, and having a column in the posts table to indicate the Editor used. 

This would allow people to use Iceberg for one post, Gutenberg for another, and even other editors like Elementor and Divi, without there being any ambiguity about which editor is going to open. The REST API is only going to increase the number of publishing flows we see invented. But that's probably something to discuss on Trac as opposed to here. 

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with the default Twenty Twenty WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
Version 5.4.1

**Comment by phpbits** [comment]
@johnstonphilip This is intentional, we made it so the editor remembers the last mode the post was edited. If you exits the post on Iceberg mode, it will automatically be loaded when you return to make changes.

If you exits Iceberg and use the default block editor then it will remember that as well.

I hope this makes sense :) Let me know your thoughts. Thanks a lot!

**Comment by johnstonphilip** [comment]
I kinda figured that :) 

For those, could you filter (using `post_row_actions`) the word "Edit" so that it shows "Edit with Iceberg", and not show the duplicate edit button?

**Comment by phpbits** [comment]
Thanks a lot for the suggestion! We will check what else we can do to improve this experience and  avoid confusions :) Thanks again!

**Comment by johnstonphilip** [comment]
I opened that thought about an Editor Registry on Trac here:

https://core.trac.wordpress.org/ticket/50214
