### ISSUE TITLE
Don't echo REST API response directly.

### ISSUE THREAD

**Issue by TimothyBJacobs** [useIceberg/iceberg-editor#9]
### Describe the bug:
The email send endpoint for the REST API uses `wp_json_encode` and sends the response itself. It should be instead returning data for the REST API server to send.

```php
if ( $sent ) {
    echo wp_json_encode( array( 'email_sent' => true ) );
} else {
    echo wp_json_encode( array( 'email_sent' => false ) );
}

die();
```

Can be changed to 

```php
return array( 'email_sent' => $sent );
```

**Comment by phpbits** [comment]
@TimothyBJacobs Thanks for reporting this issue. Will be fixed on the next update. Thanks again!
